[build]
  publish = "public"

[build.environment]
  NODE_VERSION = "14.5.0"
  YARN_VERSION = "1.22.4"

[[redirects]]
  from = "https://afara.netlify.com/*"
  to = "https://afara.foundation/:splat"
  force = true
